image: amazon/aws-cli
pipelines:
  branches:
    staging:
      - step:
          name: Test
          runs-on:
            - "self.hosted"
            - "linux"
          image: golang:1.22.3
          script:
            - make test
      - step:
          name: Build and Publish
          runs-on:
            - "self.hosted"
            - "linux"
          services:
            - docker
          script:
            - export REPO_NAME=registry-stage.qiscus.io/integration/
            - export PROJECT_NAME=caa-test-stag
            - export IMAGE_TAG="${REPO_NAME}""${PROJECT_NAME}":"${BITBUCKET_BUILD_NUMBER}"
            - docker build -t ${IMAGE_TAG} .
            - echo ${HARBOR_PASSWORD} | docker login registry-stage.qiscus.io --username ${HARBOR_USER} --password-stdin
            - docker push "${IMAGE_TAG}"
            - echo ${IMAGE_TAG}
options:
  docker: true
